# Generated by Django 4.2.6 on 2023-10-14 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Geladeira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_geladeira', models.CharField(max_length=75)),
                ('dt_criacao', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item_Geladeira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validade', models.DateField()),
                ('quantidade', models.IntegerField()),
                ('geladeira', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.geladeira')),
            ],
        ),
        migrations.CreateModel(
            name='Item_Lista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Lista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_lista', models.CharField(max_length=75)),
                ('descricao', models.TextField(max_length=700)),
                ('dt_criacao', models.DateField(auto_now=True)),
                ('geladeira', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listas', to='estoque.geladeira')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_user', models.CharField(max_length=75)),
                ('email', models.EmailField(max_length=80, unique=True)),
                ('senha', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('CARNES', 'Carnes'), ('FRUTAS', 'Frutas'), ('LATICINIOS', 'Laticínios'), ('LEGUMES', 'Legumes'), ('OVOS', 'Ovos'), ('PREPARADOS', 'Alimentos preparados')], max_length=15)),
                ('produto_geladeira', models.ManyToManyField(through='estoque.Item_Geladeira', to='estoque.geladeira')),
                ('produto_lista', models.ManyToManyField(through='estoque.Item_Lista', to='estoque.lista')),
            ],
        ),
        migrations.AddField(
            model_name='item_lista',
            name='lista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.lista'),
        ),
        migrations.AddField(
            model_name='item_lista',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.produto'),
        ),
        migrations.AddField(
            model_name='item_geladeira',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.produto'),
        ),
        migrations.AddField(
            model_name='geladeira',
            name='usuarios_proprietarios',
            field=models.ManyToManyField(to='estoque.usuario'),
        ),
    ]
