# Generated by Django 4.2.6 on 2023-10-14 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='tipo',
            field=models.CharField(choices=[('BEBIDAS', 'Bebidas'), ('CARNES', 'Carnes'), ('FRUTAS', 'Frutas'), ('LATICINIOS', 'Laticínios'), ('LEGUMES', 'Legumes'), ('OVOS', 'Ovos'), ('PREPARADOS', 'Alimentos preparados')], max_length=15),
        ),
    ]
