# Generated by Django 4.2.6 on 2023-10-14 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_alter_produto_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='imagem_produto',
            field=models.ImageField(default='default_image_produto', height_field=200, upload_to='imagens_produto', width_field=200),
        ),
    ]
