# Generated by Django 4.2.6 on 2023-10-14 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0003_produto_imagem_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='imagem_produto',
            field=models.ImageField(default='default_image_produto', upload_to='imagens_produto'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='tipo',
            field=models.CharField(choices=[('BEBIDAS', 'Bebidas'), ('BEBIDAS_ALC', 'Bebidas alcoólicas'), ('CARNES', 'Carnes'), ('FRUTAS', 'Frutas'), ('LATICINIOS', 'Laticínios'), ('LEGUMES', 'Legumes'), ('OVOS', 'Ovos'), ('PREPARADOS', 'Alimentos preparados')], max_length=15),
        ),
    ]
