# Generated by Django 4.2.6 on 2023-10-14 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0004_alter_produto_imagem_produto_alter_produto_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='unidade_medida',
            field=models.CharField(choices=[('UNIDADE', 'un'), ('GRAMA', 'g'), ('KILOGRAMA', 'kg'), ('MILILITRO', 'ml'), ('LITRO', 'lt')], default='un', max_length=20),
        ),
        migrations.AddField(
            model_name='usuario',
            name='dt_criacao',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='tipo',
            field=models.CharField(choices=[('BEBIDAS', 'Bebidas'), ('BEBIDAS_ALC', 'Bebidas alcoólicas'), ('CARNES', 'Carnes'), ('FRUTAS', 'Frutas'), ('LATICINIOS', 'Laticínios'), ('LEGUMES', 'Legumes'), ('OVOS', 'Ovos'), ('PREPARADOS', 'Alimentos preparados')], max_length=20),
        ),
    ]
