# Generated by Django 4.2.6 on 2023-10-15 12:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('estoque', '0005_produto_unidade_medida_usuario_dt_criacao_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.AlterField(
            model_name='geladeira',
            name='usuarios_proprietarios',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
