# Generated by Django 4.2.6 on 2023-10-29 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('estoque', '0007_alter_produto_imagem_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='unidade_medida',
            field=models.CharField(choices=[('UN', 'un'), ('G', 'g'), ('KG', 'kg'), ('ML', 'ml'), ('L', 'lt')], default='un', max_length=20),
        ),
        migrations.CreateModel(
            name='Log_Itens_Geladeira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_modificacao', models.DateTimeField(auto_now=True)),
                ('descricao', models.CharField(max_length=100)),
                ('item_geladeira', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.item_geladeira')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='item_geladeira',
            name='logs',
            field=models.ManyToManyField(blank=True, related_name='itens_geladeira', to='estoque.log_itens_geladeira'),
        ),
    ]
