# Generated by Django 4.2.6 on 2023-10-30 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0010_alter_log_itens_geladeira_geladeira'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log_itens_geladeira',
            name='geladeira',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.geladeira'),
        ),
    ]
